### ISSUE TITLE
Este projeto faz parte de algum Bootcamp da DIO?

### ISSUE THREAD

**Issue by gmarink** [rodolfogomes/diolive#1]
Este projeto faz parte de algum Bootcamp da DIO? ou está disponível apenas como curso (PRO)?

**Comment by rodolfogomes** [comment]
Olá, esse projeto está disponível no lab da dio para assinantes PRO.

**Comment by alfeups** [comment]
> Este projeto faz parte de algum Bootcamp da DIO? ou está disponível apenas como curso (PRO)?

Agora está disponível enquanto componente do Santander Bootcamp Fullstack.

**Comment by rodolfogomes** [comment]
Esse projeto está disponível no bootcamp do santander.
